<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <IsPackable>false</IsPackable>
    <RootNamespace>Community.PowerToys.Run.Plugin.UnicodeInput.Tests</RootNamespace>
  </PropertyGroup>
  
  <ItemGroup Condition="'$(Platform)' == 'AnyCPU' OR '$(Platform)' == 'x64'">
    <Reference Include="Wox.Plugin, Version=0.78.0.0, Culture=neutral, PublicKeyToken=null">
      <Private>True</Private>
      <HintPath>..\libs\x64\Wox.Plugin.dll</HintPath>
      <SpecificVersion>True</SpecificVersion>
      <CopyLocal>True</CopyLocal>
    </Reference>
    <Reference Include="PowerToys.Settings.UI.Lib, Version=0.76.0.0, Culture=neutral, PublicKeyToken=null">
      <Private>True</Private>
      <HintPath>..\libs\x64\PowerToys.Settings.UI.Lib.dll</HintPath>
      <SpecificVersion>True</SpecificVersion>
      <CopyLocal>True</CopyLocal>
    </Reference>
  </ItemGroup>

  <ItemGroup Condition="'$(Platform)' == 'ARM64'">
    <Reference Include="Wox.Plugin, Version=0.78.0.0, Culture=neutral, PublicKeyToken=null">
      <Private>False</Private>
      <HintPath>..\libs\ARM64\Wox.Plugin.dll</HintPath>
    </Reference>
    <Reference Include="PowerToys.Settings.UI.Lib, Version=0.76.0.0, Culture=neutral, PublicKeyToken=null">
      <Private>False</Private>
      <HintPath>..\libs\AM64\PowerToys.Settings.UI.Lib.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="MSTest.TestAdapter" />
    <PackageReference Include="MSTest.TestFramework" />
    <PackageReference Include="System.IO.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Community.PowerToys.Run.Plugin.UnicodeInput\Community.PowerToys.Run.Plugin.UnicodeInput.csproj" />
    <ProjectReference Include="..\..\UnicodeInputCore\UnicodeInput.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\Community.PowerToys.Run.Plugin.UnicodeInput\*.mapping.json">
      <Link>%(RecursiveDir)%(FileName)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>